#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Aug 02, 2017 08:47:10 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1
    
def set_Tk_var():
    
    global heure
    heure = StringVar()
    global date
    date = StringVar()
    global lib
    lib = StringVar()
    global quant
    quant = StringVar()
    global prix
    prix = StringVar()
    global mount
    mount = StringVar()
    global ddfab
    ddfab = StringVar()

def Valider(p1):
    print('Achat_produit_support.Valider')
    sys.stdout.flush()

def NvProduit(p1):
    lib.set("")
    quant.set("") 
    prix.set("")
    mount.set("")
    ddfab.set("")
    print('Achat_produit_support.NvProduit')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Achat_produit
    Achat_produit.vp_start_gui()


