#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Aug 03, 2017 03:39:25 PM
import sys
from secTest import db

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import Adherent_support
import time
import datetime
import pymysql as mysql

date = datetime.datetime.now()
mois={'1':'Janvier','2':'Fevrier','3':'Mars','4':'Avril','5':'Mai','6':'Juin',
      '7':'Juillet','8':'Aout','9':'Septembre','10':'Octobre','11':'Novembre','12':'Décembre'}
m=str(date.month)

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    Adherent_support.set_Tk_var()
    top = Mise_à_jour_adherent (root)
    Adherent_support.init(root, top)
    root.mainloop()
    
w = None
def create_Mise_à_jour_adherent(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    Adherent_support.set_Tk_var()
    top = Mise_à_jour_adherent (w)
    Adherent_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Mise_à_jour_adherent():
    global w
    w.destroy()
    w = None


class Mise_à_jour_adherent:
    def maj():
        Adherent_support.heure.set(time.strftime('%H:%M:%S'))
        root.after(1000,Mise_à_jour_adherent.maj)
    def __init__(self, top=None):
       
        
        def Nvadh():
            print(codeparrain.set(""))
            print(nomparrain.set(""))
            print(prenomparrain.set(""))
            print(codeadh.set(""))
            print(nomadh.set(""))
            print(prenomadh.set(""))
            print(datenaissadh.set(""))
            print(sexeadh.set(""))
            print(contactadh.set(""))
            print(adressadh.set(""))
            print(codepaysadh.set(""))
            print(email.set(""))
            print(nationaliteadh.set(""))
            print(droitadhesion.set(""))
            print(dateadhesion.set(""))
        def affichage():
            connexion = mysql.connect("localhost","root","","gnm" )
            cursor = connexion.cursor()
            sql = """SELECT code_nat,lib_nat FROM gnm_tb02"""
           
            try:
                #execution de la commande sql
                cursor.execute(sql)
                # selection de tous les champs 
                results = cursor.fetchall()
                for row in results:
                    codeposte = row[0]
                    codeposte=str(codeposte)
                    libpost= row[1]
                    libpost=str(libpost)
                    Adherent_support.listpost.append(codeposte)
                    Adherent_support.listnation.append(libpost)
            except:
                print("")
        affichage()

        def ajoutBdaffiche():
            contenu = [codeadh.get(),nomadh.get(),prenomadh.get(),
                       datenaissadh.get(),sexeadh.get(),contactadh.get(),
                       adressadh.get(),codepaysadh.get(),dateadhesion.get()]
            data = db()
            data.queryInsert("gnm_tb13", contenu)
            inserttreevew()
        def inserttreevew():
            #ajout dans la table
            self.listead.insert('', 1, values=(nomadh.get(),prenomadh.get(),
                                               datenaissadh.get(),sexeadh.get(),
                                               contactadh.get(),adressadh.get(),
                                               nationaliteadh.get(),codeparrain.get()))

        def modifliste():
            print(self.listead.get_children())

        def SupprimerElementListe():
            x=self.listead.selection()
            if x!="":
                y=x[0]
                v=self.listead.set(y)
                print(v)
                SQL = "DELETE FROM gnm_tb13 WHERE contact_adh =" + v['contact']
                self.cursor.execute(SQL)
                self.conn.commit()
                #data = db()
                #data.queryDeleteTo("gnm_tb13", v)
                #self.listead.delete(x)

            
        def test():
            print(codeparrain.get())
            print(nomparrain.get())
            print(prenomparrain.get())
            print(codeadh.get())
            print(nomadh.get())
            print(prenomadh.get())
            print(datenaissadh.get())
            print(sexeadh.get())
            print(contactadh.get())
            print(adressadh.get())
            print(codepaysadh.get())
            print(email.get())
            print(nationaliteadh.get())
            print(droitadhesion.get())
            print(dateadhesion.get())


        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("800x690+300+00")
        top.title("Mise à jour adherent")
        top.configure(background="#EFF0EF")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Labelframe3 = LabelFrame(top)
        self.Labelframe3.place(relx=0.04, rely=0.45, relheight=0.12
                , relwidth=0.92)
        self.Labelframe3.configure(relief=GROOVE)
        self.Labelframe3.configure(foreground="black")
        self.Labelframe3.configure(text='''Informations/Adhésion''')
        self.Labelframe3.configure(background="#EFF0EF")
        self.Labelframe3.configure(highlightbackground="#d9d9d9")
        self.Labelframe3.configure(highlightcolor="black")
        self.Labelframe3.configure(width=920)


        # adhesion infos
        self.Label5 = Label(self.Labelframe3)
        self.Label5.place(relx=0.0, rely=0.42, height=26, width=110)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#EFF0EF")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Droit d'adhesion''')

        droitadhesion = StringVar()
        self.Entry5 = Entry(self.Labelframe3)
        self.Entry5.place(relx=0.14, rely=0.42, relheight=0.25, relwidth=0.17)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3",textvariable=droitadhesion)
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(selectforeground="black")

        self.Label6 = Label(self.Labelframe3)
        self.Label6.place(relx=0.53, rely=0.44, height=26, width=141)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#EFF0EF")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Date d'adhésion''')

        dateadhesion = StringVar()
        self.Entry6 = Entry(self.Labelframe3)
        self.Entry6.place(relx=0.72, rely=0.44, relheight=0.25, relwidth=0.17)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3",textvariable=dateadhesion)
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(selectbackground="#c4c4c4")
        self.Entry6.configure(selectforeground="black")


        self.Button1 = Button(top)
        self.Button1.place(relx=0.21, rely=0.66, height=33, width=156)
        self.Button1.configure(activebackground="#218DF2")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(background="#568203")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="white")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''VALIDER''',command=ajoutBdaffiche)

        self.Button2 = Button(top)
        self.Button2.place(relx=0.6, rely=0.66, height=33, width=156)
        self.Button2.configure(activebackground="#EA8144")
        self.Button2.configure(activeforeground="white")
        self.Button2.configure(background="#723E64")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="white")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Nouvel Adherent''',command=Nvadh)

        self.Labelframe4 = LabelFrame(top)
        self.Labelframe4.place(relx=0.04, rely=0.71, relheight=0.24
                , relwidth=0.93)
        self.Labelframe4.configure(relief=GROOVE)
        self.Labelframe4.configure(foreground="black")
        self.Labelframe4.configure(text='''Liste des adhérents''')
        self.Labelframe4.configure(background="#EFF0EF")
        self.Labelframe4.configure(highlightbackground="#d9d9d9")
        self.Labelframe4.configure(highlightcolor="black")
        self.Labelframe4.configure(width=930)
        
        self.listead= ttk.Treeview(self.Labelframe4,columns=('Nom','Prenoms',
                                                             'Date de naissance','Sexe',
                                                             'contact','adresse',
                                                             'nationalité','Code parrain'))
        self.listead.column('#0',width=0)
        self.listead.column('#1',width=75)
        self.listead.column('#2',width=110)
        self.listead.column('#3',width=75)
        self.listead.column('#4',width=75)
        self.listead.column('#5',width=75)
        self.listead.column('#6',width=75)
        self.listead.column('#7',width=80)
        self.listead.column('#8',width=75)
        self.listead.heading('#1',text='Nom',anchor=CENTER)
        self.listead.heading('#2',text='Prenoms',anchor=CENTER)
        self.listead.heading('#3',text='Date de naissance',anchor=CENTER)
        self.listead.heading('#4',text='Sexe',anchor=CENTER)
        self.listead.heading('#5',text='contact',anchor=CENTER)
        self.listead.heading('#6',text='adresse',anchor=CENTER)
        self.listead.heading('#7',text='nationalité',anchor=CENTER)
        self.listead.heading('#8',text='Code parrain',anchor=CENTER)
        self.listead.grid(row=0)

        

        self.Button5 = Button(self.Labelframe4)
        self.Button5.place(relx=0.88, rely=0.17, height=33, width=89)
        self.Button5.configure(activebackground="#EA8144")
        self.Button5.configure(activeforeground="white")
        self.Button5.configure(background="#1FFED8")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="white")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''Réseaux''')

        self.Button3 = Button(self.Labelframe4)
        self.Button3.place(relx=0.88, rely=0.39, height=33, width=89)
        self.Button3.configure(activebackground="#218DF2")
        self.Button3.configure(activeforeground="white")
        self.Button3.configure(activeforeground="white")
        self.Button3.configure(background="#218DF2")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="white")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Modifier''',command=modifliste)
        self.Button3.configure(width=89)

        self.Button4 = Button(self.Labelframe4)
        self.Button4.place(relx=0.88, rely=0.61, height=33, width=89)
        self.Button4.configure(activebackground="#EA8144")
        self.Button4.configure(activeforeground="white")
        self.Button4.configure(background="#FF0921")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="white")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Supprimer''',command=SupprimerElementListe)
        
        self.Labelframe5 = LabelFrame(top)
        self.Labelframe5.place(relx=0.04, rely=0.0, relheight=0.1
                , relwidth=0.92)
        self.Labelframe5.configure(relief=GROOVE)
        self.Labelframe5.configure(foreground="black")
        self.Labelframe5.configure(text='''Info/Système''')
        self.Labelframe5.configure(background="#EFF0EF")
        self.Labelframe5.configure(highlightbackground="#d9d9d9")
        self.Labelframe5.configure(highlightcolor="black")
        self.Labelframe5.configure(width=920)

        self.Label8 = Label(self.Labelframe5)
        self.Label8.place(relx=0.82, rely=0.4, height=26, width=92)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(background="#EFF0EF")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''Heure''')
        self.Label8.configure(textvariable=Adherent_support.heure)
        Mise_à_jour_adherent.maj()

        self.Label9 = Label(self.Labelframe5)
        self.Label9.place(relx=0.77, rely=0.4, height=26, width=53)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(background="#EFF0EF")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''Heure :''')

        self.Label10 = Label(self.Labelframe5)
        self.Label10.place(relx=0.77, rely=0.0, height=26, width=45)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(background="#EFF0EF")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''Date :''')

        self.Label11 = Label(self.Labelframe5)
        self.Label11.place(relx=0.82, rely=0.0, height=26, width=82)
        self.Label11.configure(background="#EFF0EF")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(text="{0} /{1} /{2}".format(date.day,mois[m],date.year))
        self.Label11.configure(width=82)

        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.04, rely=0.1, relheight=0.11
                , relwidth=0.92)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Informations /Parrain''')
        self.Labelframe1.configure(background="#EFF0EF")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=920)

        self.Label1 = Label(self.Labelframe1)
        self.Label1.place(relx=0.03, rely=0.47, height=26, width=41)
        self.Label1.configure(activebackground="#EFF0EF")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#EFF0EF")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Code''')

        # information du parrain
        codeparrain = StringVar()
        self.Entry1 = Entry(self.Labelframe1)
        self.Entry1.place(relx=0.14, rely=0.47, relheight=0.28, relwidth=0.16)
        self.Entry1.configure(background="white",textvariable=codeparrain)
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Label3 = Label(self.Labelframe1)
        self.Label3.place(relx=0.30, rely=0.49, height=26, width=110)
        self.Label3.configure(activebackground="#EFF0EF")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#EFF0EF")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Nom''')

        nomparrain = StringVar()
        self.Entry3 = Entry(self.Labelframe1)
        self.Entry3.place(relx=0.41, rely=0.49, relheight=0.28, relwidth=0.16)
        self.Entry3.configure(background="white",textvariable=nomparrain)
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")

        self.Label4 = Label(self.Labelframe1)
        self.Label4.place(relx=0.61, rely=0.49, height=26, width=71)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#EFF0EF")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Prénom(s)''')

        prenomparrain = StringVar()
        self.Entry4 = Entry(self.Labelframe1)
        self.Entry4.place(relx=0.72, rely=0.49, relheight=0.28, relwidth=0.16)
        self.Entry4.configure(background="white",textvariable=prenomparrain)
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")


        #information adherent
        self.Labelframe2 = LabelFrame(top)
        self.Labelframe2.place(relx=0.04, rely=0.21, relheight=0.24
                , relwidth=0.92)
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Informations /Adhérent''')
        self.Labelframe2.configure(background="#EFF0EF")
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="black")
        self.Labelframe2.configure(width=921)

        self.Label12 = Label(self.Labelframe2)
        self.Label12.place(relx=0.03, rely=0.01, height=26, width=41)
        self.Label12.configure(activebackground="#EFF0EF")
        self.Label12.configure(activeforeground="black")
        self.Label12.configure(background="#EFF0EF")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(foreground="#000000")
        self.Label12.configure(highlightbackground="#d9d9d9")
        self.Label12.configure(highlightcolor="black")
        self.Label12.configure(text='''Code''')

        codeadh = StringVar()
        self.Entry8 = Entry(self.Labelframe2)
        self.Entry8.place(relx=0.14, rely=0.01, relheight=0.12, relwidth=0.16)
        self.Entry8.configure(background="white",textvariable=codeadh)
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font="TkFixedFont")
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(highlightbackground="#d9d9d9")
        self.Entry8.configure(highlightcolor="black")
        self.Entry8.configure(insertbackground="black")
        self.Entry8.configure(selectbackground="#c4c4c4")
        self.Entry8.configure(selectforeground="black")

        
        self.Label14 = Label(self.Labelframe2)
        self.Label14.place(relx=0.30, rely=0.01, height=26, width=110)
        self.Label14.configure(activebackground="#EFF0EF")
        self.Label14.configure(activeforeground="black")
        self.Label14.configure(background="#EFF0EF")
        self.Label14.configure(disabledforeground="#a3a3a3")
        self.Label14.configure(foreground="#000000")
        self.Label14.configure(highlightbackground="#d9d9d9")
        self.Label14.configure(highlightcolor="black")
        self.Label14.configure(text='''Nom''')

        nomadh = StringVar()
        self.Entry10 = Entry(self.Labelframe2)
        self.Entry10.place(relx=0.41, rely=0.01, relheight=0.12, relwidth=0.16)
        self.Entry10.configure(background="white")
        self.Entry10.configure(disabledforeground="#a3a3a3")
        self.Entry10.configure(font="TkFixedFont")
        self.Entry10.configure(foreground="#000000")
        self.Entry10.configure(highlightbackground="#d9d9d9")
        self.Entry10.configure(highlightcolor="black")
        self.Entry10.configure(insertbackground="black")
        self.Entry10.configure(selectbackground="#c4c4c4")
        self.Entry10.configure(selectforeground="black")
        self.Entry10.configure(textvariable=nomadh)

        self.Label15 = Label(self.Labelframe2)
        self.Label15.place(relx=0.61, rely=0.01, height=26, width=61)
        self.Label15.configure(activebackground="#f9f9f9")
        self.Label15.configure(activeforeground="black")
        self.Label15.configure(background="#EFF0EF")
        self.Label15.configure(disabledforeground="#a3a3a3")
        self.Label15.configure(foreground="#000000")
        self.Label15.configure(highlightbackground="#d9d9d9")
        self.Label15.configure(highlightcolor="black")
        self.Label15.configure(text='''Prénom(s)''')

        prenomadh = StringVar()
        self.Entry11 = Entry(self.Labelframe2)
        self.Entry11.place(relx=0.72, rely=0.01, relheight=0.12, relwidth=0.16)
        self.Entry11.configure(background="white",textvariable=prenomadh)
        self.Entry11.configure(disabledforeground="#a3a3a3")
        self.Entry11.configure(font="TkFixedFont")
        self.Entry11.configure(foreground="#000000")
        self.Entry11.configure(highlightbackground="#d9d9d9")
        self.Entry11.configure(highlightcolor="black")
        self.Entry11.configure(insertbackground="black")
        self.Entry11.configure(selectbackground="#c4c4c4")
        self.Entry11.configure(selectforeground="black")
        
        self.Label21 = Label(self.Labelframe2)
        self.Label21.place(relx=0.0,rely=0.28, height=26, width=110)
        self.Label21.configure(activebackground="#f9f9f9")
        self.Label21.configure(activeforeground="black")
        self.Label21.configure(background="#EFF0EF")
        self.Label21.configure(disabledforeground="#a3a3a3")
        self.Label21.configure(foreground="#000000")
        self.Label21.configure(highlightbackground="#d9d9d9")
        self.Label21.configure(highlightcolor="black")
        self.Label21.configure(text='''Date de naissance''')

        datenaissadh = StringVar()
        self.Entry16 = Entry(self.Labelframe2)
        self.Entry16.place(relx=0.14, rely=0.28, relheight=0.12, relwidth=0.16)
        self.Entry16.configure(background="white",textvariable=datenaissadh)
        self.Entry16.configure(disabledforeground="#a3a3a3")
        self.Entry16.configure(font="TkFixedFont")
        self.Entry16.configure(foreground="#000000")
        self.Entry16.configure(highlightbackground="#d9d9d9")
        self.Entry16.configure(highlightcolor="black")
        self.Entry16.configure(insertbackground="black")
        self.Entry16.configure(selectbackground="#c4c4c4")
        self.Entry16.configure(selectforeground="black")

        self.Label26 = Label(self.Labelframe2)
        self.Label26.place(relx=0.30, rely=0.28, height=26, width=110)
        self.Label26.configure(activebackground="#EFF0EF")
        self.Label26.configure(activeforeground="black")
        self.Label26.configure(background="#EFF0EF")
        self.Label26.configure(disabledforeground="#a3a3a3")
        self.Label26.configure(foreground="#000000")
        self.Label26.configure(highlightbackground="#d9d9d9")
        self.Label26.configure(highlightcolor="black")
        self.Label26.configure(text='''Sexe''')


        sexeadh = StringVar()
        self.Radiobutton5 = Radiobutton(self.Labelframe2)
        self.Radiobutton5.place(relx=0.51, rely=0.28, relheight=0.23
                , relwidth=0.05)
        self.Radiobutton5.configure(activebackground="#EFF0EF")
        self.Radiobutton5.configure(activeforeground="#000000")
        self.Radiobutton5.configure(background="#EFF0EF")
        self.Radiobutton5.configure(cursor="hand2")
        self.Radiobutton5.configure(disabledforeground="#a3a3a3")
        self.Radiobutton5.configure(foreground="#000000")
        self.Radiobutton5.configure(highlightbackground="#d9d9d9")
        self.Radiobutton5.configure(highlightcolor="black")
        self.Radiobutton5.configure(justify=LEFT)
        self.Radiobutton5.configure(text='''F''')
        self.Radiobutton5.configure(value="F")
        self.Radiobutton5.configure(variable=sexeadh)
        
        
        self.Radiobutton6 = Radiobutton(self.Labelframe2)
        self.Radiobutton6.place(relx=0.42, rely=0.28, relheight=0.23
                , relwidth=0.05)
        self.Radiobutton6.configure(activebackground="#EFF0EF")
        self.Radiobutton6.configure(activeforeground="#000000")
        self.Radiobutton6.configure(background="#EFF0EF")
        self.Radiobutton6.configure(cursor="hand2")
        self.Radiobutton6.configure(disabledforeground="#a3a3a3")
        self.Radiobutton6.configure(foreground="#000000")
        self.Radiobutton6.configure(highlightbackground="#d9d9d9")
        self.Radiobutton6.configure(highlightcolor="black")
        self.Radiobutton6.configure(justify=LEFT)
        self.Radiobutton6.configure(state=ACTIVE)
        self.Radiobutton6.configure(text='''M''')
        self.Radiobutton6.configure(value="M")
        self.Radiobutton6.configure(variable=sexeadh)

        self.Label97 = Label(self.Labelframe2)
        self.Label97.place(relx=0.0,rely=0.58, height=26, width=110)
        self.Label97.configure(activebackground="#f9f9f9")
        self.Label97.configure(activeforeground="black")
        self.Label97.configure(background="#EFF0EF")
        self.Label97.configure(disabledforeground="#a3a3a3")
        self.Label97.configure(foreground="#000000")
        self.Label97.configure(highlightbackground="#d9d9d9")
        self.Label97.configure(highlightcolor="black")
        self.Label97.configure(text='''Contact''')

        contactadh = StringVar()
        self.Entry97 = Entry(self.Labelframe2)
        self.Entry97.place(relx=0.14
                           , rely=0.58, relheight=0.12, relwidth=0.16)
        self.Entry97.configure(background="white")
        self.Entry97.configure(disabledforeground="#a3a3a3",textvariable=contactadh)
        self.Entry97.configure(font="TkFixedFont")
        self.Entry97.configure(foreground="#000000")
        self.Entry97.configure(highlightbackground="#d9d9d9")
        self.Entry97.configure(highlightcolor="black")
        self.Entry97.configure(insertbackground="black")
        self.Entry97.configure(selectbackground="#c4c4c4")
        self.Entry97.configure(selectforeground="black")


        self.Label98 = Label(self.Labelframe2)
        self.Label98.place(relx=0.30,rely=0.58, height=26, width=110)
        self.Label98.configure(activebackground="#f9f9f9")
        self.Label98.configure(activeforeground="black")
        self.Label98.configure(background="#EFF0EF")
        self.Label98.configure(disabledforeground="#a3a3a3")
        self.Label98.configure(foreground="#000000")
        self.Label98.configure(highlightbackground="#d9d9d9")
        self.Label98.configure(highlightcolor="black")
        self.Label98.configure(text='''Adresse''')


        adressadh = StringVar()
        self.Entry98 = Entry(self.Labelframe2)
        self.Entry98.place(relx=0.41
                           , rely=0.58, relheight=0.12, relwidth=0.16)
        self.Entry98.configure(background="white")
        self.Entry98.configure(disabledforeground="#a3a3a3",textvariable=adressadh)
        self.Entry98.configure(font="TkFixedFont")
        self.Entry98.configure(foreground="#000000")
        self.Entry98.configure(highlightbackground="#d9d9d9")
        self.Entry98.configure(highlightcolor="black")
        self.Entry98.configure(insertbackground="black")
        self.Entry98.configure(selectbackground="#c4c4c4")
        self.Entry98.configure(selectforeground="black")

        self.Label198 = Label(self.Labelframe2)
        self.Label198.place(relx=0.61,rely=0.58, height=26, width=61)
        self.Label198.configure(activebackground="#f9f9f9")
        self.Label198.configure(activeforeground="black")
        self.Label198.configure(background="#EFF0EF")
        self.Label198.configure(disabledforeground="#a3a3a3")
        self.Label198.configure(foreground="#000000")
        self.Label198.configure(highlightbackground="#d9d9d9")
        self.Label198.configure(highlightcolor="black")
        self.Label198.configure(text='''N° pièce''')

        codepaysadh = StringVar()
        self.nationalite=ttk.Combobox(self.Labelframe2,textvariable=codepaysadh,values=Adherent_support.listpost).place(relx=0.72,rely=0.58, height=26, width=110)
        

        self.Label117 = Label(self.Labelframe2)
        self.Label117.place(relx=0.0,rely=0.8, height=26, width=110)
        self.Label117.configure(activebackground="#f9f9f9")
        self.Label117.configure(activeforeground="black",textvariable=codepaysadh)
        self.Label117.configure(background="#EFF0EF")
        self.Label117.configure(disabledforeground="#a3a3a3")
        self.Label117.configure(foreground="#000000")
        self.Label117.configure(highlightbackground="#d9d9d9")
        self.Label117.configure(highlightcolor="black")
        self.Label117.configure(text=''' E-mail''')

        email = StringVar()
        self.Label117 = Entry(self.Labelframe2)
        self.Label117.place(relx=0.14, rely=0.825, relheight=0.12, relwidth=0.16)
        self.Label117.configure(background="white")
        self.Label117.configure(disabledforeground="#a3a3a3")
        self.Label117.configure(font="TkFixedFont")
        self.Label117.configure(foreground="#000000")
        self.Label117.configure(highlightbackground="#d9d9d9")
        self.Label117.configure(highlightcolor="black")
        self.Label117.configure(insertbackground="black")
        self.Label117.configure(selectbackground="#c4c4c4")
        self.Label117.configure(selectforeground="black")
        #self.Label117.configure(textvariable=email)

        
        self.Label117 = Label(self.Labelframe2)
        self.Label117.place(relx=0.30,rely=0.8, height=26, width=110)
        self.Label117.configure(activebackground="#f9f9f9")
        self.Label117.configure(activeforeground="black")
        self.Label117.configure(background="#EFF0EF")
        self.Label117.configure(disabledforeground="#a3a3a3")
        self.Label117.configure(foreground="#000000")
        self.Label117.configure(highlightbackground="#d9d9d9")
        self.Label117.configure(highlightcolor="black")
        self.Label117.configure(text=''' Nationnalite''')

        nationaliteadh = StringVar()
        self.nationalite=ttk.Combobox(self.Labelframe2,textvariable=nationaliteadh,values=Adherent_support.listnation).place(relx=0.43,rely=0.8, height=26, width=110)




if __name__ == '__main__':
    vp_start_gui()



