#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Aug 03, 2017 03:39:33 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global heure
    heure = StringVar()
    global date
    date = StringVar()
    global nom
    nom = StringVar()
    global prenom
    prenom = StringVar()
    global ddnaiss
    ddnaiss = StringVar()
    global sexe
    sexe = StringVar()
    global contact
    contact = StringVar()
    global adresse
    adresse = StringVar()
    global nationalite
    nationalite = StringVar()
    global Npiece
    Npiece = StringVar()
    global Email
    Email = StringVar()
    global listpost
    listpost=list()
    global listnation
    listnation=list()

def Valider(p1):
    print('Adherent_support.Valider')
    sys.stdout.flush()

def quitter(p1):
    print('Adherent_support.quitter')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Adherent
    Adherent.vp_start_gui()


