#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Aug 01, 2017 02:25:07 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1
    
import Employe_support
import datetime
import time
date = datetime.datetime.now()
mois={'1':'Janvier','2':'Fevrier','3':'Mars','4':'Avril','5':'Mai','6':'Juin',
      '7':'Juillet','8':'Aout','9':'Septembre','10':'Octobre','11':'Novembre','12':'Décembre'}
m=str(date.month)

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    Employe_support.set_Tk_var()
    top = Mise_à_jour_employé (root)
    Employe_support.init(root, top)
    root.mainloop()

w = None
def create_Mise_à_jour_employé(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    Employe_support.set_Tk_var()
    top = Mise_à_jour_employé (w)
    Employe_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Mise_à_jour_employé():
    global w
    w.destroy()
    w = None


class Mise_à_jour_employé:
    def maj():
        Employe_support.heure.set(time.strftime('%H:%M:%S'))
        root.after(1000,Mise_à_jour_employé.maj)
    def __init__(self, top=None):

        def inserer():

            self.listead.insert('', 1, values=(Employe_support.nom.get(),Employe_support.prenom.get(),Employe_support.ddnaiss.get()
                                   ,Employe_support.sexe.get(),Employe_support.contact.get()))
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("960x788+300+00")
        top.title("Mise à jour employé")
        top.configure(background="#EFF0EF")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Labelframe3 = LabelFrame(top)
        self.Labelframe3.place(relx=0.04, rely=0.365, relheight=0.12
                , relwidth=0.92)
        self.Labelframe3.configure(relief=GROOVE)
        self.Labelframe3.configure(foreground="black")
        self.Labelframe3.configure(text='''Informations/embauche''')
        self.Labelframe3.configure(background="#EFF0EF")
        self.Labelframe3.configure(highlightbackground="#d9d9d9")
        self.Labelframe3.configure(highlightcolor="black")
        self.Labelframe3.configure(width=920)

        self.Label5 = Label(self.Labelframe3)
        self.Label5.place(relx=0.04, rely=0.42, height=26, width=36)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#EFF0EF")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Pote''')

        self.Entry5 = Entry(self.Labelframe3)
        self.Entry5.place(relx=0.14, rely=0.42, relheight=0.25, relwidth=0.17)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(selectforeground="black")

        self.Label6 = Label(self.Labelframe3)
        self.Label6.place(relx=0.53, rely=0.44, height=26, width=141)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#EFF0EF")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Date d'embauche''')

        self.Entry6 = Entry(self.Labelframe3)
        self.Entry6.place(relx=0.72, rely=0.44, relheight=0.25, relwidth=0.17)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(selectbackground="#c4c4c4")
        self.Entry6.configure(selectforeground="black")

        self.Label7 = Label(self.Labelframe3)
        self.Label7.place(relx=0.04, rely=1.28, height=26, width=71)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#EFF0EF")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Capacité''')

        self.Entry7 = Entry(self.Labelframe3)
        self.Entry7.place(relx=0.14, rely=1.28, relheight=0.25, relwidth=0.17)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(highlightbackground="#d9d9d9")
        self.Entry7.configure(highlightcolor="black")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(selectbackground="#c4c4c4")
        self.Entry7.configure(selectforeground="black")

        self.Button1 = Button(top)
        self.Button1.place(relx=0.26, rely=0.63, height=33, width=156)
        self.Button1.configure(activebackground="#218DF2")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(background="#218DF2")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="white")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''VALIDER''',command=inserer)
        self.Button1.bind('<Button-1>',lambda e:Employe_support.Valider(e))

        self.Button2 = Button(top)
        self.Button2.place(relx=0.6, rely=0.63, height=33, width=156)
        self.Button2.configure(activebackground="#EA8144")
        self.Button2.configure(activeforeground="white")
        self.Button2.configure(background="#EA8144")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="white")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''+ADHERENT''')
        self.Button2.bind('<Button-1>',lambda e:Employe_support.NvEmploye(e))

        self.Labelframe4 = LabelFrame(top)
        self.Labelframe4.place(relx=0.03, rely=0.68, relheight=0.24
                , relwidth=0.93)
        self.Labelframe4.configure(relief=GROOVE)
        self.Labelframe4.configure(foreground="black")
        self.Labelframe4.configure(text='''Liste des employés''')
        self.Labelframe4.configure(background="#EFF0EF")
        self.Labelframe4.configure(highlightbackground="#d9d9d9")
        self.Labelframe4.configure(highlightcolor="black")
        self.Labelframe4.configure(width=930)

        self.listead= ttk.Treeview(self.Labelframe4,columns=('Nom','Prenom','Date de naissance','Sexe','Contact','Adresse','Poste'))
        self.listead.column('#0',width=0)
        self.listead.column('#1',width=105)
        self.listead.column('#2',width=130)
        self.listead.column('#3',width=115)
        self.listead.column('#4',width=50)
        self.listead.column('#5',width=80)
        self.listead.column('#6',width=100)
        self.listead.column('#7',width=60)
        self.listead.heading('#1',text='Nom',anchor=CENTER)
        self.listead.heading('#2',text='Prenoms',anchor=CENTER)
        self.listead.heading('#3',text='Date de naissance',anchor=CENTER)
        self.listead.heading('#4',text='Sexe',anchor=CENTER)
        self.listead.heading('#5',text='contact',anchor=CENTER)
        self.listead.heading('#6',text='adresse',anchor=CENTER)
        self.listead.heading('#7',text='Poste',anchor=CENTER)
        self.listead.grid(row=0)

        self.Button3 = Button(self.Labelframe4)
        self.Button3.place(relx=0.85, rely=0.36, height=33, width=89)
        self.Button3.configure(activebackground="#218DF2")
        self.Button3.configure(activeforeground="white")
        self.Button3.configure(activeforeground="white")
        self.Button3.configure(background="#218DF2")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="white")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Modifier''')
        self.Button3.configure(width=89)

        self.Button4 = Button(self.Labelframe4)
        self.Button4.place(relx=0.85, rely=0.57, height=33, width=89)
        self.Button4.configure(activebackground="#EA8144")
        self.Button4.configure(activeforeground="white")
        self.Button4.configure(background="#EA8144")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="white")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Supprimer''')

        self.Labelframe5 = LabelFrame(top)
        self.Labelframe5.place(relx=0.04, rely=0.01, relheight=0.08
                , relwidth=0.92)
        self.Labelframe5.configure(relief=GROOVE)
        self.Labelframe5.configure(foreground="black")
        self.Labelframe5.configure(text='''Info/Système''')
        self.Labelframe5.configure(background="#EFF0EF")
        self.Labelframe5.configure(highlightbackground="#d9d9d9")
        self.Labelframe5.configure(highlightcolor="black")
        self.Labelframe5.configure(width=920)

        self.Label8 = Label(self.Labelframe5)
        self.Label8.place(relx=0.82, rely=0.4, height=26, width=92)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(background="#EFF0EF")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''Heure''')
        self.Label8.configure(textvariable=Employe_support.heure)
        Mise_à_jour_employé.maj()

        self.Label9 = Label(self.Labelframe5)
        self.Label9.place(relx=0.77, rely=0.4, height=26, width=53)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(background="#EFF0EF")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''Heure :''')

        self.Label10 = Label(self.Labelframe5)
        self.Label10.place(relx=0.77, rely=0.0, height=26, width=45)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(background="#EFF0EF")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''Date :''')

        self.Label11 = Label(self.Labelframe5)
        self.Label11.place(relx=0.82, rely=0.0, height=26, width=82)
        self.Label11.configure(background="#EFF0EF")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(text="{0} /{1} /{2}".format(date.day,mois[m],date.year))
        self.Label11.configure(width=82)

        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.04, rely=0.1, relheight=0.26
                , relwidth=0.92)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Informations /employé''')
        self.Labelframe1.configure(background="#EFF0EF")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=920)

        self.Label1 = Label(self.Labelframe1)
        self.Label1.place(relx=0.03, rely=0.2, height=26, width=89)
        self.Label1.configure(activebackground="#EFF0EF")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#EFF0EF")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''N° matricule''')

        self.Label2 = Label(self.Labelframe1)
        self.Label2.place(relx=0.03, rely=0.5, height=26, width=61)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#EFF0EF")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Prénoms''')

        self.Entry1 = Entry(self.Labelframe1)
        self.Entry1.place(relx=0.14, rely=0.2, relheight=0.12, relwidth=0.16)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")
        self.Entry1.configure(textvariable=Employe_support.Nmat)

        self.Entry2 = Entry(self.Labelframe1)
        self.Entry2.place(relx=0.14, rely=0.5, relheight=0.12, relwidth=0.16)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")
        self.Entry2.configure(textvariable=Employe_support.prenom)

        self.Label3 = Label(self.Labelframe1)
        self.Label3.place(relx=0.5, rely=0.25, height=26, width=89)
        self.Label3.configure(activebackground="#EFF0EF")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#EFF0EF")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Nom''')

        self.Entry3 = Entry(self.Labelframe1)
        self.Entry3.place(relx=0.62, rely=0.25, relheight=0.12, relwidth=0.16)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")
        self.Entry3.configure(textvariable=Employe_support.nom)

        self.Label4 = Label(self.Labelframe1)
        self.Label4.place(relx=0.52, rely=0.5, height=26, width=61)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#EFF0EF")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Contact''')

        self.Entry4 = Entry(self.Labelframe1)
        self.Entry4.place(relx=0.62, rely=0.5, relheight=0.12, relwidth=0.16)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")
        self.Entry4.configure(textvariable=Employe_support.contact)

        self.Label21 = Label(self.Labelframe1)
        self.Label21.place(relx=0.0, rely=0.84, height=26, width=131)
        self.Label21.configure(activebackground="#f9f9f9")
        self.Label21.configure(activeforeground="black")
        self.Label21.configure(background="#EFF0EF")
        self.Label21.configure(disabledforeground="#a3a3a3")
        self.Label21.configure(foreground="#000000")
        self.Label21.configure(highlightbackground="#d9d9d9")
        self.Label21.configure(highlightcolor="black")
        self.Label21.configure(text='''Date de naissance''')

        self.Entry16 = Entry(self.Labelframe1)
        self.Entry16.place(relx=0.14, rely=0.84, relheight=0.12, relwidth=0.16)
        self.Entry16.configure(background="white")
        self.Entry16.configure(disabledforeground="#a3a3a3")
        self.Entry16.configure(font="TkFixedFont")
        self.Entry16.configure(foreground="#000000")
        self.Entry16.configure(highlightbackground="#d9d9d9")
        self.Entry16.configure(highlightcolor="black")
        self.Entry16.configure(insertbackground="black")
        self.Entry16.configure(selectbackground="#c4c4c4")
        self.Entry16.configure(selectforeground="black")
        self.Entry16.configure(textvariable=Employe_support.ddnaiss)

        self.Label22 = Label(self.Labelframe1)
        self.Label22.place(relx=0.53, rely=0.79, height=26, width=61)
        self.Label22.configure(activebackground="#EFF0EF")
        self.Label22.configure(activeforeground="black")
        self.Label22.configure(background="#EFF0EF")
        self.Label22.configure(disabledforeground="#a3a3a3")
        self.Label22.configure(foreground="#000000")
        self.Label22.configure(highlightbackground="#d9d9d9")
        self.Label22.configure(highlightcolor="black")
        self.Label22.configure(text='''Sexe''')

        self.Radiobutton3 = Radiobutton(self.Labelframe1)
        self.Radiobutton3.place(relx=0.7, rely=0.79, relheight=0.15
                , relwidth=0.05)
        self.Radiobutton3.configure(activebackground="#EFF0EF")
        self.Radiobutton3.configure(activeforeground="#000000")
        self.Radiobutton3.configure(background="#EFF0EF")
        self.Radiobutton3.configure(cursor="hand2")
        self.Radiobutton3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3.configure(foreground="#000000")
        self.Radiobutton3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3.configure(highlightcolor="black")
        self.Radiobutton3.configure(justify=LEFT)
        self.Radiobutton3.configure(text='''F''')
        self.Radiobutton3.configure(value="F")
        self.Radiobutton3.configure(variable=Employe_support.sexe)

        self.Radiobutton4 = Radiobutton(self.Labelframe1)
        self.Radiobutton4.place(relx=0.61, rely=0.78, relheight=0.15
                , relwidth=0.05)
        self.Radiobutton4.configure(activebackground="#EFF0EF")
        self.Radiobutton4.configure(activeforeground="#000000")
        self.Radiobutton4.configure(background="#EFF0EF")
        self.Radiobutton4.configure(cursor="hand2")
        self.Radiobutton4.configure(disabledforeground="#a3a3a3")
        self.Radiobutton4.configure(foreground="#000000")
        self.Radiobutton4.configure(highlightbackground="#d9d9d9")
        self.Radiobutton4.configure(highlightcolor="black")
        self.Radiobutton4.configure(justify=LEFT)
        self.Radiobutton4.configure(state=ACTIVE)
        self.Radiobutton4.configure(text='''M''')
        self.Radiobutton4.configure(value="M")
        self.Radiobutton4.configure(variable=Employe_support.sexe)

        self.Labelframe6 = LabelFrame(top)
        self.Labelframe6.place(relx=0.04, rely=0.495, relheight=0.12
                , relwidth=0.92)
        self.Labelframe6.configure(relief=GROOVE)
        self.Labelframe6.configure(foreground="black")
        self.Labelframe6.configure(text='''Information/adhérents''')
        self.Labelframe6.configure(background="#EFF0EF")
        self.Labelframe6.configure(highlightbackground="#d9d9d9")
        self.Labelframe6.configure(highlightcolor="black")
        self.Labelframe6.configure(width=920)

        self.Label23 = Label(self.Labelframe6)
        self.Label23.place(relx=0.01, rely=0.42, height=26, width=116)
        self.Label23.configure(activebackground="#f9f9f9")
        self.Label23.configure(activeforeground="black")
        self.Label23.configure(background="#EFF0EF")
        self.Label23.configure(disabledforeground="#a3a3a3")
        self.Label23.configure(foreground="#000000")
        self.Label23.configure(highlightbackground="#d9d9d9")
        self.Label23.configure(highlightcolor="black")
        self.Label23.configure(text='''Code d'adhesion''')

        self.Entry17 = Entry(self.Labelframe6)
        self.Entry17.place(relx=0.15, rely=0.42, relheight=0.25, relwidth=0.17)
        self.Entry17.configure(background="white")
        self.Entry17.configure(disabledforeground="#a3a3a3")
        self.Entry17.configure(font="TkFixedFont")
        self.Entry17.configure(foreground="#000000")
        self.Entry17.configure(highlightbackground="#d9d9d9")
        self.Entry17.configure(highlightcolor="black")
        self.Entry17.configure(insertbackground="black")
        self.Entry17.configure(selectbackground="#c4c4c4")
        self.Entry17.configure(selectforeground="black")

        self.Label24 = Label(self.Labelframe6)
        self.Label24.place(relx=0.53, rely=0.44, height=26, width=141)
        self.Label24.configure(activebackground="#f9f9f9")
        self.Label24.configure(activeforeground="black")
        self.Label24.configure(background="#EFF0EF")
        self.Label24.configure(disabledforeground="#a3a3a3")
        self.Label24.configure(foreground="#000000")
        self.Label24.configure(highlightbackground="#d9d9d9")
        self.Label24.configure(highlightcolor="black")
        self.Label24.configure(text='''Date d'adhesion''')

        self.Entry18 = Entry(self.Labelframe6)
        self.Entry18.place(relx=0.72, rely=0.44, relheight=0.25, relwidth=0.17)
        self.Entry18.configure(background="white")
        self.Entry18.configure(disabledforeground="#a3a3a3")
        self.Entry18.configure(font="TkFixedFont")
        self.Entry18.configure(foreground="#000000")
        self.Entry18.configure(highlightbackground="#d9d9d9")
        self.Entry18.configure(highlightcolor="black")
        self.Entry18.configure(insertbackground="black")
        self.Entry18.configure(selectbackground="#c4c4c4")
        self.Entry18.configure(selectforeground="black")

        self.Label25 = Label(self.Labelframe6)
        self.Label25.place(relx=0.04, rely=1.28, height=26, width=71)
        self.Label25.configure(activebackground="#f9f9f9")
        self.Label25.configure(activeforeground="black")
        self.Label25.configure(background="#EFF0EF")
        self.Label25.configure(disabledforeground="#a3a3a3")
        self.Label25.configure(foreground="#000000")
        self.Label25.configure(highlightbackground="#d9d9d9")
        self.Label25.configure(highlightcolor="black")
        self.Label25.configure(text='''Capacité''')

        self.Entry19 = Entry(self.Labelframe6)
        self.Entry19.place(relx=0.14, rely=1.28, relheight=0.25, relwidth=0.17)
        self.Entry19.configure(background="white")
        self.Entry19.configure(disabledforeground="#a3a3a3")
        self.Entry19.configure(font="TkFixedFont")
        self.Entry19.configure(foreground="#000000")
        self.Entry19.configure(highlightbackground="#d9d9d9")
        self.Entry19.configure(highlightcolor="black")
        self.Entry19.configure(insertbackground="black")
        self.Entry19.configure(selectbackground="#c4c4c4")
        self.Entry19.configure(selectforeground="black")






if __name__ == '__main__':
    vp_start_gui()



