#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Aug 01, 2017 02:25:25 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global heure
    heure = StringVar()
    global date
    date = StringVar()
    global Nmat
    Nmat = StringVar()
    global nom
    nom = StringVar()
    global prenom
    prenom = StringVar()
    global contact
    contact = StringVar()
    global ddnaiss
    ddnaiss = StringVar()
    global sexe
    sexe = StringVar()
    

def Valider(p1):
    print('Employe_support.Valider')
    sys.stdout.flush()

def NvEmploye(p1):
    Nmat.set("")
    nom.set("")
    prenom.set("")
    contact.set("")
    ddnaiss.set("")
    sexe.set("")
    
    print('Achat_produit_support.quitter')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Employe
    Employe.vp_start_gui()


