#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Aug 01, 2017 07:10:29 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import Emplacement_support
import time
import datetime

date = datetime.datetime.now()
mois={'1':'Janvier','2':'Fevrier','3':'Mars','4':'Avril','5':'Mai','6':'Juin',
      '7':'Juillet','8':'Aout','9':'Septembre','10':'Octobre','11':'Novembre','12':'Décembre'}
m=str(date.month)

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    Emplacement_support.set_Tk_var()
    top = Emplacement (root)
    Emplacement_support.init(root, top)
    root.mainloop()

w = None
def create_Emplacement(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    Emplacement_support.set_Tk_var()
    top = Emplacement (w)
    Emplacement_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Emplacement():
    global w
    w.destroy()
    w = None


class Emplacement:
    def maj():
        Emplacement_support.heure.set(time.strftime('%H:%M:%S'))
        root.after(1000,Emplacement.maj)
    def __init__(self, top=None):
        def inserer():

            self.listead.insert('', 1, values=(Emplacement_support.lib.get(),Emplacement_support.capacite.get(),Emplacement_support.codemag.get()))
            
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("960x788+300+00")
        top.title("Emplacement")
        top.configure(background="#EFF0EF")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.04, rely=0.1, relheight=0.23
                , relwidth=0.92)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Magasin''')
        self.Labelframe1.configure(background="#EFF0EF")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=920)

        self.Label1 = Label(self.Labelframe1)
        self.Label1.place(relx=0.03, rely=0.22, height=26, width=41)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#EFF0EF")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Code''')

        self.Label2 = Label(self.Labelframe1)
        self.Label2.place(relx=0.02, rely=0.61, height=26, width=61)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#EFF0EF")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Libéllé''')

        self.Entry1 = Entry(self.Labelframe1)
        self.Entry1.place(relx=0.14, rely=0.22, relheight=0.13, relwidth=0.16)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")
        self.Entry1.configure(textvariable=Emplacement_support.codemag)

        self.Entry2 = Entry(self.Labelframe1)
        self.Entry2.place(relx=0.14, rely=0.61, relheight=0.13, relwidth=0.16)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")

        self.Labelframe2 = LabelFrame(self.Labelframe1)
        self.Labelframe2.place(relx=0.59, rely=0.11, relheight=0.68
                , relwidth=0.33)
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Position''')
        self.Labelframe2.configure(background="#EFF0EF")
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="black")
        self.Labelframe2.configure(width=300)

        self.Label3 = Label(self.Labelframe2)
        self.Label3.place(relx=0.1, rely=0.24, height=26, width=73)
        self.Label3.configure(activebackground="#EFF0EF")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#EFF0EF")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Longitude''')

        self.Label4 = Label(self.Labelframe2)
        self.Label4.place(relx=0.1, rely=0.66, height=26, width=73)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#EFF0EF")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Lagitude''')

        self.Entry3 = Entry(self.Labelframe2)
        self.Entry3.place(relx=0.5, rely=0.24, relheight=0.19, relwidth=0.38)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")

        self.Entry4 = Entry(self.Labelframe2)
        self.Entry4.place(relx=0.5, rely=0.66, relheight=0.19, relwidth=0.38)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")

        self.Labelframe3 = LabelFrame(top)
        self.Labelframe3.place(relx=0.04, rely=0.35, relheight=0.24
                , relwidth=0.92)
        self.Labelframe3.configure(relief=GROOVE)
        self.Labelframe3.configure(foreground="black")
        self.Labelframe3.configure(text='''Emplacement''')
        self.Labelframe3.configure(background="#EFF0EF")
        self.Labelframe3.configure(highlightbackground="#d9d9d9")
        self.Labelframe3.configure(highlightcolor="black")
        self.Labelframe3.configure(width=920)

        self.Label5 = Label(self.Labelframe3)
        self.Label5.place(relx=0.04, rely=0.21, height=26, width=41)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#EFF0EF")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Code''')

        self.Entry5 = Entry(self.Labelframe3)
        self.Entry5.place(relx=0.14, rely=0.21, relheight=0.12, relwidth=0.17)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(selectforeground="black")
        self.Entry5.configure(textvariable=Emplacement_support.code)

        self.Label6 = Label(self.Labelframe3)
        self.Label6.place(relx=0.61, rely=0.22, height=26, width=71)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#EFF0EF")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Libéllé''')

        self.Entry6 = Entry(self.Labelframe3)
        self.Entry6.place(relx=0.72, rely=0.22, relheight=0.12, relwidth=0.17)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(selectbackground="#c4c4c4")
        self.Entry6.configure(selectforeground="black")
        self.Entry6.configure(textvariable=Emplacement_support.lib)

        self.Label7 = Label(self.Labelframe3)
        self.Label7.place(relx=0.04, rely=0.63, height=26, width=71)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#EFF0EF")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Capacité''')

        self.Entry7 = Entry(self.Labelframe3)
        self.Entry7.place(relx=0.14, rely=0.63, relheight=0.12, relwidth=0.17)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(highlightbackground="#d9d9d9")
        self.Entry7.configure(highlightcolor="black")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(selectbackground="#c4c4c4")
        self.Entry7.configure(selectforeground="black")
        self.Entry7.configure(textvariable=Emplacement_support.capacite)

        self.Button1 = Button(top)
        self.Button1.place(relx=0.26, rely=0.61, height=33, width=156)
        self.Button1.configure(activebackground="#218DF2")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(background="#218DF2")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="white")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''VALIDER''',command=inserer)
        self.Button1.bind('<Button-1>',lambda e:Emplacement_support.Valider(e))

        self.Button2 = Button(top)
        self.Button2.place(relx=0.62, rely=0.61, height=33, width=156)
        self.Button2.configure(activebackground="#EA8144")
        self.Button2.configure(activeforeground="white")
        self.Button2.configure(background="#EA8144")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="white")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''+ MAGASIN''')
        self.Button2.bind('<Button-1>',lambda e:Emplacement_support.NvMag(e))

        self.Labelframe4 = LabelFrame(top)
        self.Labelframe4.place(relx=0.03, rely=0.68, relheight=0.24
                , relwidth=0.93)
        self.Labelframe4.configure(relief=GROOVE)
        self.Labelframe4.configure(foreground="black")
        self.Labelframe4.configure(text='''Liste des emplacements''')
        self.Labelframe4.configure(background="#EFF0EF")
        self.Labelframe4.configure(highlightbackground="#d9d9d9")
        self.Labelframe4.configure(highlightcolor="black")
        self.Labelframe4.configure(width=930)
        
        self.listead= ttk.Treeview(self.Labelframe4,columns=('Libéllé','Capacité',' Code magasin'))
        self.listead.column('#0',width=0)
        self.listead.column('#1',width=250)
        self.listead.column('#2',width=250)
        self.listead.column('#3',width=200)
        self.listead.heading('#1',text='Libéllé',anchor=CENTER)
        self.listead.heading('#2',text='Capacité',anchor=CENTER)
        self.listead.heading('#3',text='Code magasin',anchor=CENTER)
        self.listead.grid(row=0)

        self.Button3 = Button(self.Labelframe4)
        self.Button3.place(relx=0.84, rely=0.1, height=33, width=89)
        self.Button3.configure(activebackground="#218DF2")
        self.Button3.configure(activeforeground="white")
        self.Button3.configure(activeforeground="white")
        self.Button3.configure(background="#218DF2")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="white")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Modifier''')
        self.Button3.configure(width=89)

        self.Button4 = Button(self.Labelframe4)
        self.Button4.place(relx=0.84, rely=0.63, height=33, width=89)
        self.Button4.configure(activebackground="#EA8144")
        self.Button4.configure(activeforeground="white")
        self.Button4.configure(background="#EA8144")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="white")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Supprimer''')

        self.Labelframe5 = LabelFrame(top)
        self.Labelframe5.place(relx=0.04, rely=0.01, relheight=0.08
                , relwidth=0.92)
        self.Labelframe5.configure(relief=GROOVE)
        self.Labelframe5.configure(foreground="black")
        self.Labelframe5.configure(text='''Informations système''')
        self.Labelframe5.configure(background="#EFF0EF")
        self.Labelframe5.configure(width=920)

        self.Label8 = Label(self.Labelframe5)
        self.Label8.place(relx=0.82, rely=0.4, height=26, width=92)
        self.Label8.configure(background="#EFF0EF")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''Heure''')
        self.Label8.configure(textvariable=Emplacement_support.heure)
        Emplacement.maj()
        self.Label8.configure(width=92)

        self.Label9 = Label(self.Labelframe5)
        self.Label9.place(relx=0.77, rely=0.4, height=26, width=53)
        self.Label9.configure(background="#EFF0EF")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(text='''Heure :''')

        self.Label10 = Label(self.Labelframe5)
        self.Label10.place(relx=0.77, rely=0.0, height=26, width=45)
        self.Label10.configure(background="#EFF0EF")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(text='''Date :''')

        self.Label11 = Label(self.Labelframe5)
        self.Label11.place(relx=0.82, rely=0.0, height=26, width=82)
        self.Label11.configure(background="#EFF0EF")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(text="{0} /{1} /{2}".format(date.day,mois[m],date.year))
        self.Label11.configure(width=82)






if __name__ == '__main__':
    vp_start_gui()



