#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Aug 02, 2017 04:22:30 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global heure
    heure = StringVar()
    global date
    date = StringVar()
    global cmpte
    cmpte = StringVar()
    global mdp
    mdp= StringVar()
    global utilisateur
    utilisateur=StringVar()
    global motdepasse
    motdepasse= StringVar()
    global reponse
    
    
    
    
def connecte(p1):
    
    print('Main_ecr_support.connecte')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Main_ecr
    Main_ecr.vp_start_gui()


