#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Aug 02, 2017 01:10:32 PM


import sys

try:
    from Tkinter import *
    from tkinter.messagebox import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global heure
    heure = StringVar()
    global date
    date = StringVar()
    global codeposte
    codeposte=StringVar()
    global libpost
    libpost=StringVar()
    global reponse
    global test
    test=StringVar()
    
def Nvposte(p1):
    
    codeposte.set("")
    libpost.set("") 
    print('nv poste ok')
    sys.stdout.flush()

def Valider(p1):
    print('Postes_support.Valider')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Postes
    Postes.vp_start_gui()


