#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Aug 02, 2017 02:53:11 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import Stockage_produit_support
import time
import datetime

date = datetime.datetime.now()
mois={'1':'Janvier','2':'Fevrier','3':'Mars','4':'Avril','5':'Mai','6':'Juin',
      '7':'Juillet','8':'Aout','9':'Septembre','10':'Octobre','11':'Novembre','12':'Décembre'}
m=str(date.month)

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    Stockage_produit_support.set_Tk_var()
    top = Stockage_de_produits (root)
    Stockage_produit_support.init(root, top)
    root.mainloop()

w = None
def create_Stockage_de_produits(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    Stockage_produit_support.set_Tk_var()
    top = Stockage_de_produits (w)
    Stockage_produit_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Stockage_de_produits():
    global w
    w.destroy()
    w = None


class Stockage_de_produits:
    def maj():
        Stockage_produit_support.heure.set(time.strftime('%H:%M:%S'))
        root.after(1000,Stockage_de_produits.maj)
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("960x788+300+00")
        top.title("Stockage de produits")
        top.configure(background="#EFF0EF")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.04, rely=0.09, relheight=0.15
                , relwidth=0.92)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Magasin''')
        self.Labelframe1.configure(background="#EFF0EF")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=920)

        self.Label1 = Label(self.Labelframe1)
        self.Label1.place(relx=0.03, rely=0.32, height=26, width=41)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#EFF0EF")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Code''')

        self.Label2 = Label(self.Labelframe1)
        self.Label2.place(relx=0.03, rely=0.66, height=26, width=61)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#EFF0EF")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Libéllé''')

        self.Entry1 = Entry(self.Labelframe1)
        self.Entry1.place(relx=0.14, rely=0.32, relheight=0.19, relwidth=0.16)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Entry2 = Entry(self.Labelframe1)
        self.Entry2.place(relx=0.14, rely=0.66, relheight=0.19, relwidth=0.16)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")

        self.Label3 = Label(self.Labelframe1)
        self.Label3.place(relx=0.51, rely=0.5, height=26, width=171)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#EFF0EF")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Nombre d'emplacement''')

        self.Entry3 = Entry(self.Labelframe1)
        self.Entry3.place(relx=0.72, rely=0.5, relheight=0.19, relwidth=0.16)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")

        self.Labelframe3 = LabelFrame(top)
        self.Labelframe3.place(relx=0.04, rely=0.25, relheight=0.15
                , relwidth=0.92)
        self.Labelframe3.configure(relief=GROOVE)
        self.Labelframe3.configure(foreground="black")
        self.Labelframe3.configure(text='''Emplacement''')
        self.Labelframe3.configure(background="#EFF0EF")
        self.Labelframe3.configure(highlightbackground="#d9d9d9")
        self.Labelframe3.configure(highlightcolor="black")
        self.Labelframe3.configure(width=920)

        self.Label5 = Label(self.Labelframe3)
        self.Label5.place(relx=0.04, rely=0.32, height=26, width=41)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#EFF0EF")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Code''')

        self.Entry5 = Entry(self.Labelframe3)
        self.Entry5.place(relx=0.14, rely=0.32, relheight=0.19, relwidth=0.17)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(selectforeground="black")

        self.Label6 = Label(self.Labelframe3)
        self.Label6.place(relx=0.61, rely=0.34, height=26, width=71)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#EFF0EF")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Libéllé''')

        self.Entry6 = Entry(self.Labelframe3)
        self.Entry6.place(relx=0.73, rely=0.34, relheight=0.19, relwidth=0.17)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(selectbackground="#c4c4c4")
        self.Entry6.configure(selectforeground="black")

        self.Entry7 = Entry(self.Labelframe3)
        self.Entry7.place(relx=0.14, rely=0.66, relheight=0.19, relwidth=0.17)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(highlightbackground="#d9d9d9")
        self.Entry7.configure(highlightcolor="black")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(selectbackground="#c4c4c4")
        self.Entry7.configure(selectforeground="black")

        self.Label7 = Label(self.Labelframe3)
        self.Label7.place(relx=0.03, rely=0.66, height=26, width=71)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#EFF0EF")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Capacité''')

        self.Label16 = Label(self.Labelframe3)
        self.Label16.place(relx=0.58, rely=0.66, height=26, width=131)
        self.Label16.configure(activebackground="#f9f9f9")
        self.Label16.configure(activeforeground="black")
        self.Label16.configure(background="#EFF0EF")
        self.Label16.configure(disabledforeground="#a3a3a3")
        self.Label16.configure(foreground="#000000")
        self.Label16.configure(highlightbackground="#d9d9d9")
        self.Label16.configure(highlightcolor="black")
        self.Label16.configure(text='''Quantité actuelle''')

        self.Entry11 = Entry(self.Labelframe3)
        self.Entry11.place(relx=0.73, rely=0.66, relheight=0.19, relwidth=0.17)
        self.Entry11.configure(background="white")
        self.Entry11.configure(disabledforeground="#a3a3a3")
        self.Entry11.configure(font="TkFixedFont")
        self.Entry11.configure(foreground="#000000")
        self.Entry11.configure(highlightbackground="#d9d9d9")
        self.Entry11.configure(highlightcolor="black")
        self.Entry11.configure(insertbackground="black")
        self.Entry11.configure(selectbackground="#c4c4c4")
        self.Entry11.configure(selectforeground="black")

        self.Button1 = Button(top)
        self.Button1.place(relx=0.14, rely=0.67, height=33, width=156)
        self.Button1.configure(activebackground="#218DF2")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(background="#218DF2")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="white")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''VALIDER''')
        self.Button1.bind('<Button-1>',lambda e:Stockage_produit_support.Valider(e))

        self.Button2 = Button(top)
        self.Button2.place(relx=0.64, rely=0.67, height=33, width=156)
        self.Button2.configure(activebackground="#EA8144")
        self.Button2.configure(activeforeground="white")
        self.Button2.configure(background="#EA8144")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="white")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''+ MAGASIN''')
        self.Button2.bind('<Button-1>',lambda e:Stockage_produit_support.quitter(e))

        self.Labelframe4 = LabelFrame(top)
        self.Labelframe4.place(relx=0.04, rely=0.72, relheight=0.23
                , relwidth=0.93)
        self.Labelframe4.configure(relief=GROOVE)
        self.Labelframe4.configure(foreground="black")
        self.Labelframe4.configure(text='''Liste des produits''')
        self.Labelframe4.configure(background="#EFF0EF")
        self.Labelframe4.configure(highlightbackground="#d9d9d9")
        self.Labelframe4.configure(highlightcolor="black")
        self.Labelframe4.configure(width=930)

        self.listead= ttk.Treeview(self.Labelframe4,columns=('Libéllé','Famille produit','Date de stockage','Forme produit','Quantité','Population visée'))
        self.listead.column('#0',width=0)
        self.listead.column('#1',width=125)
        self.listead.column('#2',width=150)
        self.listead.column('#3',width=135)
        self.listead.column('#4',width=100)
        self.listead.column('#5',width=100)
        self.listead.column('#6',width=120)
        self.listead.heading('#1',text='Libéllé',anchor=CENTER)
        self.listead.heading('#2',text='Famille produit',anchor=CENTER)
        self.listead.heading('#3',text='Date de stockage',anchor=CENTER)
        self.listead.heading('#4',text='Forme produit',anchor=CENTER)
        self.listead.heading('#5',text='Quantité',anchor=CENTER)
        self.listead.heading('#6',text='Population visée',anchor=CENTER)
        self.listead.grid(row=0)

        self.Button3 = Button(self.Labelframe4)
        self.Button3.place(relx=0.84, rely=0.1, height=33, width=89)
        self.Button3.configure(activebackground="#218DF2")
        self.Button3.configure(activeforeground="white")
        self.Button3.configure(activeforeground="white")
        self.Button3.configure(background="#218DF2")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="white")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Modifier''')
        self.Button3.configure(width=89)

        self.Button4 = Button(self.Labelframe4)
        self.Button4.place(relx=0.84, rely=0.63, height=33, width=89)
        self.Button4.configure(activebackground="#EA8144")
        self.Button4.configure(activeforeground="white")
        self.Button4.configure(background="#EA8144")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="white")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Supprimer''')

        self.Labelframe5 = LabelFrame(top)
        self.Labelframe5.place(relx=0.04, rely=0.01, relheight=0.08
                , relwidth=0.92)
        self.Labelframe5.configure(relief=GROOVE)
        self.Labelframe5.configure(foreground="black")
        self.Labelframe5.configure(text='''Labelframe''')
        self.Labelframe5.configure(background="#EFF0EF")
        self.Labelframe5.configure(highlightbackground="#d9d9d9")
        self.Labelframe5.configure(highlightcolor="black")
        self.Labelframe5.configure(width=920)

        self.Label8 = Label(self.Labelframe5)
        self.Label8.place(relx=0.82, rely=0.4, height=26, width=92)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(background="#EFF0EF")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''Heure''')
        self.Label8.configure(textvariable=Stockage_produit_support.heure)
        Stockage_de_produits.maj()

        self.Label9 = Label(self.Labelframe5)
        self.Label9.place(relx=0.77, rely=0.4, height=26, width=53)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(background="#EFF0EF")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''Heure :''')

        self.Label10 = Label(self.Labelframe5)
        self.Label10.place(relx=0.77, rely=0.0, height=26, width=45)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(background="#EFF0EF")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''Date :''')

        self.Label11 = Label(self.Labelframe5)
        self.Label11.place(relx=0.82, rely=0.0, height=26, width=82)
        self.Label11.configure(background="#EFF0EF")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(text="{0} /{1} /{2}".format(date.day,mois[m],date.year))
        self.Label11.configure(width=82)

        self.Button5 = Button(top)
        self.Button5.place(relx=0.39, rely=0.67, height=33, width=156)
        self.Button5.configure(activebackground="#939594")
        self.Button5.configure(activeforeground="white")
        self.Button5.configure(background="#939594")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="white")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''+EMPLACEMENT''')

        self.Labelframe6 = LabelFrame(top)
        self.Labelframe6.place(relx=0.04, rely=0.4, relheight=0.25
                , relwidth=0.92)
        self.Labelframe6.configure(relief=GROOVE)
        self.Labelframe6.configure(foreground="black")
        self.Labelframe6.configure(text='''Stockage des produits''')
        self.Labelframe6.configure(background="#EFF0EF")
        self.Labelframe6.configure(highlightbackground="#d9d9d9")
        self.Labelframe6.configure(highlightcolor="black")
        self.Labelframe6.configure(width=920)

        self.Label17 = Label(self.Labelframe6)
        self.Label17.place(relx=0.04, rely=0.19, height=26, width=41)
        self.Label17.configure(activebackground="#f9f9f9")
        self.Label17.configure(activeforeground="black")
        self.Label17.configure(background="#EFF0EF")
        self.Label17.configure(disabledforeground="#a3a3a3")
        self.Label17.configure(foreground="#000000")
        self.Label17.configure(highlightbackground="#d9d9d9")
        self.Label17.configure(highlightcolor="black")
        self.Label17.configure(text='''Code''')

        self.Entry12 = Entry(self.Labelframe6)
        self.Entry12.place(relx=0.15, rely=0.19, relheight=0.11, relwidth=0.17)
        self.Entry12.configure(background="white")
        self.Entry12.configure(disabledforeground="#a3a3a3")
        self.Entry12.configure(font="TkFixedFont")
        self.Entry12.configure(foreground="#000000")
        self.Entry12.configure(highlightbackground="#d9d9d9")
        self.Entry12.configure(highlightcolor="black")
        self.Entry12.configure(insertbackground="black")
        self.Entry12.configure(selectbackground="#c4c4c4")
        self.Entry12.configure(selectforeground="black")

        self.Label18 = Label(self.Labelframe6)
        self.Label18.place(relx=0.36, rely=0.2, height=26, width=71)
        self.Label18.configure(activebackground="#f9f9f9")
        self.Label18.configure(activeforeground="black")
        self.Label18.configure(background="#EFF0EF")
        self.Label18.configure(disabledforeground="#a3a3a3")
        self.Label18.configure(foreground="#000000")
        self.Label18.configure(highlightbackground="#d9d9d9")
        self.Label18.configure(highlightcolor="black")
        self.Label18.configure(text='''Libéllé''')

        self.Entry13 = Entry(self.Labelframe6)
        self.Entry13.place(relx=0.46, rely=0.2, relheight=0.11, relwidth=0.17)
        self.Entry13.configure(background="white")
        self.Entry13.configure(disabledforeground="#a3a3a3")
        self.Entry13.configure(font="TkFixedFont")
        self.Entry13.configure(foreground="#000000")
        self.Entry13.configure(highlightbackground="#d9d9d9")
        self.Entry13.configure(highlightcolor="black")
        self.Entry13.configure(insertbackground="black")
        self.Entry13.configure(selectbackground="#c4c4c4")
        self.Entry13.configure(selectforeground="black")

        self.Entry14 = Entry(self.Labelframe6)
        self.Entry14.place(relx=0.15, rely=0.47, relheight=0.11, relwidth=0.17)
        self.Entry14.configure(background="white")
        self.Entry14.configure(disabledforeground="#a3a3a3")
        self.Entry14.configure(font="TkFixedFont")
        self.Entry14.configure(foreground="#000000")
        self.Entry14.configure(highlightbackground="#d9d9d9")
        self.Entry14.configure(highlightcolor="black")
        self.Entry14.configure(insertbackground="black")
        self.Entry14.configure(selectbackground="#c4c4c4")
        self.Entry14.configure(selectforeground="black")

        self.Label19 = Label(self.Labelframe6)
        self.Label19.place(relx=0.01, rely=0.47, height=26, width=121)
        self.Label19.configure(activebackground="#f9f9f9")
        self.Label19.configure(activeforeground="black")
        self.Label19.configure(background="#EFF0EF")
        self.Label19.configure(disabledforeground="#a3a3a3")
        self.Label19.configure(foreground="#000000")
        self.Label19.configure(highlightbackground="#d9d9d9")
        self.Label19.configure(highlightcolor="black")
        self.Label19.configure(text='''Date de stockage''')

        self.Label20 = Label(self.Labelframe6)
        self.Label20.place(relx=0.34, rely=0.43, height=26, width=131)
        self.Label20.configure(activebackground="#f9f9f9")
        self.Label20.configure(activeforeground="black")
        self.Label20.configure(background="#EFF0EF")
        self.Label20.configure(disabledforeground="#a3a3a3")
        self.Label20.configure(foreground="#000000")
        self.Label20.configure(highlightbackground="#d9d9d9")
        self.Label20.configure(highlightcolor="black")
        self.Label20.configure(text='''Quantité''')

        self.Entry15 = Entry(self.Labelframe6)
        self.Entry15.place(relx=0.46, rely=0.43, relheight=0.11, relwidth=0.17)
        self.Entry15.configure(background="white")
        self.Entry15.configure(disabledforeground="#a3a3a3")
        self.Entry15.configure(font="TkFixedFont")
        self.Entry15.configure(foreground="#000000")
        self.Entry15.configure(highlightbackground="#d9d9d9")
        self.Entry15.configure(highlightcolor="black")
        self.Entry15.configure(insertbackground="black")
        self.Entry15.configure(selectbackground="#c4c4c4")
        self.Entry15.configure(selectforeground="black")

        self.Label21 = Label(self.Labelframe6)
        self.Label21.place(relx=0.67, rely=0.2, height=26, width=131)
        self.Label21.configure(activebackground="#f9f9f9")
        self.Label21.configure(activeforeground="black")
        self.Label21.configure(background="#EFF0EF")
        self.Label21.configure(disabledforeground="#a3a3a3")
        self.Label21.configure(foreground="#000000")
        self.Label21.configure(highlightbackground="#d9d9d9")
        self.Label21.configure(highlightcolor="black")
        self.Label21.configure(text='''Famille produit''')

        self.Label22 = Label(self.Labelframe6)
        self.Label22.place(relx=0.67, rely=0.43, height=26, width=131)
        self.Label22.configure(activebackground="#f9f9f9")
        self.Label22.configure(activeforeground="black")
        self.Label22.configure(background="#EFF0EF")
        self.Label22.configure(disabledforeground="#a3a3a3")
        self.Label22.configure(foreground="#000000")
        self.Label22.configure(highlightbackground="#d9d9d9")
        self.Label22.configure(highlightcolor="black")
        self.Label22.configure(text='''Forme produit''')

        self.Label23 = Label(self.Labelframe6)
        self.Label23.place(relx=0.01, rely=0.66, height=26, width=151)
        self.Label23.configure(activebackground="#f9f9f9")
        self.Label23.configure(activeforeground="black")
        self.Label23.configure(background="#EFF0EF")
        self.Label23.configure(disabledforeground="#a3a3a3")
        self.Label23.configure(foreground="#000000")
        self.Label23.configure(highlightbackground="#d9d9d9")
        self.Label23.configure(highlightcolor="black")
        self.Label23.configure(text='''Population concernée''')
        self.Label23.configure(width=151)

        self.TCombobox1 = ttk.Combobox(self.Labelframe6)
        self.TCombobox1.place(relx=0.82, rely=0.19, relheight=0.12
                , relwidth=0.17)
        self.TCombobox1.configure(textvariable=Stockage_produit_support.combobox)
        self.TCombobox1.configure(width=157)
        self.TCombobox1.configure(takefocus="")

        self.TCombobox3 = ttk.Combobox(self.Labelframe6)
        self.TCombobox3.place(relx=0.82, rely=0.43, relheight=0.12
                , relwidth=0.17)
        self.TCombobox3.configure(textvariable=Stockage_produit_support.combobox)
        self.TCombobox3.configure(width=157)
        self.TCombobox3.configure(takefocus="")

        self.style.map('TCheckbutton',background=
            [('selected', _bgcolor), ('active',"_ana2color")])
        
        self.TCheckbutton1 = Checkbutton(self.Labelframe6)
        self.TCheckbutton1.place(relx=0.21, rely=0.65, relwidth=0.08
                , relheight=0.0, height=26)
        self.TCheckbutton1.configure(variable=Stockage_produit_support.tch50)
        self.TCheckbutton1.configure(takefocus="")
        self.TCheckbutton1.configure(text='''Homme''')

        self.TCheckbutton2 = Checkbutton(self.Labelframe6)
        self.TCheckbutton2.place(relx=0.37, rely=0.66, relwidth=0.08
                , relheight=0.0, height=26)
        self.TCheckbutton2.configure(variable=Stockage_produit_support.tch51)
        self.TCheckbutton2.configure(takefocus="")
        self.TCheckbutton2.configure(text='''Femme''')

        self.TCheckbutton3 = Checkbutton(self.Labelframe6)
        self.TCheckbutton3.place(relx=0.53, rely=0.66, relwidth=0.08
                , relheight=0.0, height=26)
        self.TCheckbutton3.configure(variable=Stockage_produit_support.tch52)
        self.TCheckbutton3.configure(takefocus="")
        self.TCheckbutton3.configure(text='''Enfant''')

        self.TCheckbutton4 = Checkbutton(self.Labelframe6)
        self.TCheckbutton4.place(relx=0.71, rely=0.66, relwidth=0.08
                , relheight=0.0, height=26)
        self.TCheckbutton4.configure(variable=Stockage_produit_support.tch53)
        self.TCheckbutton4.configure(takefocus="")
        self.TCheckbutton4.configure(text='''Vieux''')






if __name__ == '__main__':
    vp_start_gui()



