#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Aug 02, 2017 02:53:17 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global heure
    heure = StringVar()
    global date
    date = StringVar()
    global combobox
    combobox = StringVar()
    global tch50
    tch50 = StringVar()
    global tch51
    tch51 = StringVar()
    global tch52
    tch52 = StringVar()
    global tch53
    tch53 = StringVar()

def Valider(p1):
    print('Stockage_produit_support.Valider')
    sys.stdout.flush()

def quitter(p1):
    print('Stockage_produit_support.quitter')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Stockage_produit
    Stockage_produit.vp_start_gui()


